In [190]:
#Using numpy module
import numpy as np

In [191]:
#creating array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1,arr2)

[1 2 3] [4 5 6]


In [192]:
#Addition of array
sumarr = arr1+2
sumarr2 = arr1+arr2
print(sumarr,sumarr2)

[3 4 5] [5 7 9]


In [193]:
#Subtraction
subarr = arr2-1
subarr2 = arr2-arr1
print(subarr,subarr)

[3 4 5] [3 4 5]


In [194]:
#Multiplication
mularr = arr1*100
mularr2 = arr1*arr2
print(mularr,mularr2)

[100 200 300] [ 4 10 18]


In [195]:
#Division
divarr = arr1/2
divarr2 = arr2/arr1
print(divarr,divarr2)

[0.5 1.  1.5] [4.  2.5 2. ]


In [196]:
#Creating Random numbers array
random = np.random.rand(10)
print(random)

[0.14369335 0.94824791 0.65643243 0.80829642 0.98791314 0.51601874
 0.8474225  0.10373017 0.98925319 0.40524849]


In [197]:
#Finding size of array
arr1.size

3

In [198]:
#Multi-Dimension Array
marr1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
marr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(marr1,"\n",marr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [199]:
marr1.ndim

2

In [200]:
salary = np.array(([1,2,3],[4,5,6]))
print(salary)

[[1 2 3]
 [4 5 6]]


In [201]:
salary = salary+salary*0.10

In [202]:
print(salary)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [203]:
print(salary.shape)

(2, 3)


In [204]:
rang = np.arange(100)
print(rang)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [205]:
rang2 = np.arange(100).reshape(2,2,5,5)
print(rang2)

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]
   [10 11 12 13 14]
   [15 16 17 18 19]
   [20 21 22 23 24]]

  [[25 26 27 28 29]
   [30 31 32 33 34]
   [35 36 37 38 39]
   [40 41 42 43 44]
   [45 46 47 48 49]]]


 [[[50 51 52 53 54]
   [55 56 57 58 59]
   [60 61 62 63 64]
   [65 66 67 68 69]
   [70 71 72 73 74]]

  [[75 76 77 78 79]
   [80 81 82 83 84]
   [85 86 87 88 89]
   [90 91 92 93 94]
   [95 96 97 98 99]]]]


In [206]:
print(rang2.ndim)

4


In [207]:
rang2.mean()

49.5

In [208]:
rang2.nbytes

400

In [209]:
print(rang2.max())

99


In [210]:
ran = np.arange(0,100).reshape(10,10)
print(ran)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [211]:
print(ran.min(0)) # 0 for column
print(ran.min(1)) # 1 for row
print(ran.min())

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0


In [212]:
rang2.newbyteorder()

array([[[[         0,   16777216,   33554432,   50331648,   67108864],
         [  83886080,  100663296,  117440512,  134217728,  150994944],
         [ 167772160,  184549376,  201326592,  218103808,  234881024],
         [ 251658240,  268435456,  285212672,  301989888,  318767104],
         [ 335544320,  352321536,  369098752,  385875968,  402653184]],

        [[ 419430400,  436207616,  452984832,  469762048,  486539264],
         [ 503316480,  520093696,  536870912,  553648128,  570425344],
         [ 587202560,  603979776,  620756992,  637534208,  654311424],
         [ 671088640,  687865856,  704643072,  721420288,  738197504],
         [ 754974720,  771751936,  788529152,  805306368,  822083584]]],


       [[[ 838860800,  855638016,  872415232,  889192448,  905969664],
         [ 922746880,  939524096,  956301312,  973078528,  989855744],
         [1006632960, 1023410176, 1040187392, 1056964608, 1073741824],
         [1090519040, 1107296256, 1124073472, 1140850688, 1157627904],


In [213]:
np.ones((3,3,3,3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [214]:
np.zeros((5,5,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [215]:
arr1 = []
i = 0
m = int(input("Enter no. of columns : "))
while i<m:
    x = eval(input("Enter the ele : "))
    arr1.append(x)
    i+=1
    
arr = np.array(arr1)
print(arr)

Enter no. of columns : 


ValueError: invalid literal for int() with base 10: ''

In [216]:
#TypeCasting
c = np.array(([1,2,3,4,5,6]),dtype = float)

In [217]:
print(c)

[1. 2. 3. 4. 5. 6.]


In [218]:
arr7 = np.zeros((3,2,4))
print(arr7)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [219]:
#horizontal splitting
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [220]:
np.median(arr7)

0.0

In [221]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [222]:
arr0 = np.array([int(input("Enter the ele : ")) for i in range(10)]).reshape(2,5)

Enter the ele : 


ValueError: invalid literal for int() with base 10: ''

In [223]:
arr0

NameError: name 'arr0' is not defined

In [224]:
[i/1000 for i in range(1,100000) if (i%10.5==0 and i%11.5==0 and i%12.5==0)]

[12.075, 24.15, 36.225, 48.3, 60.375, 72.45, 84.525, 96.6]

In [225]:
np.logspace(1,10,4)

array([1.e+01, 1.e+04, 1.e+07, 1.e+10])

In [226]:
arr9 = np.array([[[[[1,2],[3,4]]]]])

In [227]:
arr9.ndim

5

In [228]:
arr9.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [229]:
arr9.ndim

5

In [230]:
arr9.T #transpose of the matrix

array([[[[[1]]],


        [[[3]]]],



       [[[[2]]],


        [[[4]]]]])

In [231]:
np.sin(arr9)

array([[[[[ 0.84147098,  0.90929743],
          [ 0.14112001, -0.7568025 ]]]]])

In [232]:
np.cos(arr9)

array([[[[[ 0.54030231, -0.41614684],
          [-0.9899925 , -0.65364362]]]]])

In [233]:
np.tan(arr9)

array([[[[[ 1.55740772, -2.18503986],
          [-0.14254654,  1.15782128]]]]])

In [234]:
arr1 = np.arange(100).reshape(10,10)
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [235]:
arr1[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [236]:
arr1[9:,9]

array([99])

In [237]:
arr1[9:10]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [238]:
arr1[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
arr1[:10,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [240]:
arr1[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [241]:
print(arr1[6:7,4],arr1[6:7,5])

[64] [65]


In [242]:
print(arr1[5:6,0],arr1[5:6,1],arr1[7:8,8],arr1[8:9,8])

[50] [51] [78] [88]


In [243]:
print(arr1[5,0:2],arr1[7:9,8])

[50 51] [78 88]


In [244]:
#from function
np.fromfunction(lambda x,y:x+y,(3,3),dtype=float)

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [245]:
arr1.diagonal()

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [246]:
arr1.diagonal(offset = 4)

array([ 4, 15, 26, 37, 48, 59])

In [247]:
arr1.diagonal(offset = 3, axis1 = 1, axis2 = 0)

array([30, 41, 52, 63, 74, 85, 96])

In [248]:
arr1.diagonal(offset = -3)

array([30, 41, 52, 63, 74, 85, 96])

In [249]:
#Identity
np.identity(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [250]:
def arr(x,y):
    return x+y*10

In [251]:
np.fromfunction(arr,(3,3),dtype=int)

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22]])

In [252]:
def arr1(w,x,y,z):
    return x+y

In [253]:
np.fromfunction(arr1,(2,2,3,3),dtype=int)

array([[[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]],


       [[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]]])

In [254]:
np.fromfunction(arr1,(2,2,3,3),dtype=int).ndim

4

In [267]:
arr2 = np.arange(100).reshape(10,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [272]:
arr2.argmin(1) #Index of min value

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [269]:
arr2.argmax(1) #Index of max value

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9], dtype=int64)

In [276]:
np.empty(5)

array([2.12199579e-313, 6.36598737e-313, 1.06099790e-312, 1.48539705e-312,
       1.90979621e-312])

In [277]:
np.matrix(arr2)

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [278]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [281]:
arr2.argsort()

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int64)

In [282]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [285]:
arr2.sort()

In [288]:
randarr = np.random.rand(100).reshape(10,10)
print(randarr)

[[0.55426328 0.94018978 0.65764377 0.98925387 0.66694538 0.75948212
  0.39602007 0.72184582 0.18963947 0.91143226]
 [0.49861528 0.09501296 0.41105166 0.47722355 0.55051594 0.87383387
  0.05677536 0.2028126  0.33224887 0.08639527]
 [0.98449264 0.17012125 0.00303025 0.8062678  0.21550489 0.59901587
  0.64906158 0.41735379 0.449974   0.95000315]
 [0.70629231 0.16034607 0.84785497 0.47914532 0.14455666 0.43974107
  0.77994796 0.91971118 0.15680849 0.45880013]
 [0.55759727 0.3544356  0.96593805 0.18621079 0.43649436 0.65751037
  0.70096834 0.5623547  0.19747384 0.15342923]
 [0.6167035  0.46082079 0.8289939  0.04865897 0.25202863 0.89947741
  0.67959723 0.48978759 0.36533741 0.83532625]
 [0.26279926 0.8431114  0.180061   0.12573157 0.4473269  0.91764164
  0.72788987 0.51997686 0.56503384 0.8791455 ]
 [0.0535994  0.74509071 0.12549797 0.35532071 0.90101746 0.20881274
  0.69434859 0.98843135 0.23357811 0.87147156]
 [0.86625309 0.83410684 0.80554486 0.2827036  0.03688807 0.2752095
  0.65318008 

In [301]:
randarr[7,7] #no at 7th index

0.9884313507166134

In [307]:
np.random.seed(0) 
np.random.rand(9).reshape(3,3)


array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [313]:
np.random.randint(10,size=(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [323]:
#linear algebra
from numpy import *

In [319]:
inv(randarr)

array([[-0.45461448,  0.08987336,  0.38148052,  0.12261372,  0.35836377,
        -0.35324384, -0.2688181 , -0.64465212,  0.21397604,  1.3224561 ],
       [ 0.59951592, -0.61545476, -0.42468624,  0.02046403,  0.43890413,
        -1.08763705,  0.99825601, -0.83625713,  0.26556407,  0.69077151],
       [ 0.31617844,  0.15936472, -0.40565966, -0.28128839, -0.28230188,
         1.35605303, -1.15232229,  0.59002551,  0.34847558, -0.70920063],
       [ 0.89273834, -0.16543566,  0.46858385, -0.1091591 ,  0.22563854,
        -0.67968041, -0.04022998,  0.0225038 , -0.04703141, -0.8774686 ],
       [-0.30847728,  0.40319897,  0.4675408 , -1.54459098,  1.0892061 ,
         0.48594258, -1.19537179,  1.17423211, -0.05059507, -0.02209562],
       [ 0.2171664 ,  0.13683656, -0.12086986,  0.32522574,  0.37465018,
        -0.44579041,  1.25772837, -1.0541856 , -0.70801988,  0.20530175],
       [ 0.0199583 , -1.55489184,  1.24002347, -1.18222706,  2.67339255,
        -0.77223962,  0.41570586,  0.0126226 

In [321]:
'''
Linear eqn
3 * x0 + x1 = 9
x0 + 2 * x1 = 8
'''
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [329]:
root = np.linalg.solve(a,b)
print(root) #root type is array 

[2. 3.]


In [339]:
c = inv(a)*b 
print(c)

[[ 3.6 -1.6]
 [-1.8  4.8]]


In [341]:
a = np.arange(10)
np.where(a<4,a,10*a)

array([ 0,  1,  2,  3, 40, 50, 60, 70, 80, 90])

In [343]:
for i in arr2.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [346]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [351]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [353]:
arr2.var()

833.25

In [354]:
arr2.std()

28.86607004772212